import React, {Component} from 'react'
import {connect} from 'react-redux'

export default class AboutMe extends Component {
  render() {
    return (
      <div>
        <div>
          <div className="names">
            DR. DENNIS DEPERRO '77 TIMOTHY KELLY TRISTAN D'AMGELO THERESA SCHUTA
            DANIEL CAULFIELD CHRISTOPHER RUSIN MARGE CARROLL MAUREEN DIGGINS JOE
            HEAD '69 REV. GREG JAKUBOWICS '83 MICHAEL LEMPKO '84 THE HILLERY
            FAMILY THE WHALEN FAMILY MICHAEL LUCARELLI JOHN COLLINS ESQ. '64
            ROBERT CHAMBERS MEL PALANO MARTY MALONEY '91 MAUREEN MYERS WILLIAM
            MURPHY, ESQ '89 BRIAN PILARSKI '01 BJ RYAN '98 BONNIE AND JERRY
            SULLIVAN PETERY CLANCY '79 THOMAS SULLIVAN '75 SR. MARY ELLEN TWIST,
            RSM REV. RICHARD "DUKE" ZAJAC ERIK BOHEN '00 STEVEN HIETANEN,DDS '80
            REV. THOMAS QUINLIVAN '63 DAVID "WARD" SCARCWELLO '76 PATRICK
            STANTON '69 DAVE POWERS JIM BOURIS BILL CONROY '78  GENE OVERDORF
            '71 BARBARA HART DR. PETER PURCELL '74 SR. PEGGEY GORMAN RSM JIM
            PALANO MARK CASSIFY '77 PAT and JOE CROWLEY '53 JACK DEVINE '54 TOM
            GRAHAM '59 JACK JERGE '52 TOM MCDONNELL '86 MICHAEL BURKE HENRY
            DEMICKE '54 REV. EDWARD DURKIN SJ REV. JAMES JUDGE MARGARET OVERDORF
            MAUREEN WINNERT MATT BURKE '80 MICHAEL DIGGINS '60 NEIL FARREL '75
            RAY MCGURN '69 MARK REED '89 BETTY EAGEN THOMAN HIGGINS THOMAS
            MCCARTHY BARBARA RYAN PATRICK FITZGERALD JOHN HOFFSTETTER JAMED C.
            TILLEY '59 SISTER ELLEN O'KEEFE S.S.J. MARY ELLEN and TOM REILLY '62
            REV.WILLIAM BIGELOW DAN FINUCANE CARL and CATHY PALADINO MSGR. DAVID
            M. LEE SUE AND TED OVERDORF MARGARET "PEG" SULLIVAN SISTER SALLY
            WALTZ, RSM PAUL AND VICKI BARBUS RICHARD ROBINSON SR. '52 FATHER
            JOEL A. CAMPBELL, O.F.M. MSGR.WILLIAM J. GALLAGHER '57 KAREN and
            CHARLIE WILSON '61 JUNE BARNES PAUL FITZPATRICK '66 REV. MSGR.
            ROBERT C. WURTZ, PA FR. JOE BAYNE O.F.M JOHN GLOSE '68 MARK
            SCHROEDER '74 REV JOHN ALDERSON O.F.M. JOSEPH CRANGLE ESQ. '50
            MATTHEW COLPOYS '55 JOSEPH CROWLEY JOHN (JACK) HEITZHAUS PATRICK
            SHINE NORMAN KERSCH RICH ROBILLARD MARTIN "MARTY' WINNERT JR. JIM
            and DOLORES MALONEY JACK REID ALFRED "ALFIE" B. WRIGHT SR. HONORABLE
            JACK QUINN JERRY WHALEN. ESQ ROBERT "HOPPER" RUSH JAMES R. HILLERY
            WILLIAM (DUKE) FORSYTHE REV. MSGR. JAMES F. CAMPBELL JOHN J. "NOEY"
            NOSTRANT RICHARD DONOVAN DOROTHY PANKOW MSGR. BASIL A. ORMSBY D.D.
            SISTER BARBARA CIARICO R.S.M HON. KEVIN M. DILLON JACK CHILCOTT REV.
            MSGR. S. THEODORE BERG DOMINIC and IDA CHELLA ELIZABETH MADDIGAN
            BRIAN M. HIGGINS ROBERT H. CHAMBERS REV. MSGR. WILLIAM G. STANTON
            LOUIS J. NILLITTIER RT. REV. MSGR. DINO J. LORENZETTI COLONEL HENRY
            F. WILLIAMS REV. VENARD CARR O.F.M. REV HUGH HINES O.F.M SR. MARY
            WALTER LOVE S.S.J KENNETH J. BRAUN SR. ELLEN MAHON R.S.M. SR. M.
            BERCHMANS MCDONOUGH R.S.M. SR. M. JEAN. BAPTIST TRINOR R.S.M SR.
            SHEILA MARIE WALSH R.S.M JAMES M. CONNORS DANIEL DRISCOLL GEORGE
            ELLIS MICHAEL LICATA MEL PALANO GERALI A. WHALEN ROBERT H. CHAMBERS
            WALTER J. MAHONEY ERNEST L. COLUCCI WILLIAM D. HASSERR JR. REV. MSGR
            LEO E. HAMMERL RICHARD F. TORREY SR. MARY MECHTILDE R.S.M. P.E.P
            JOSEPH V. BROCATO THE MOST REVERAND JAMES A. MCNULTY D.D. PETER GUST
            ECONOMOU ANTHONY L. MIKULEC REV. JAMES J. REDMOND S.J. MRS. EDWARD
            H. COTTRELL PASCHAL C. RUBINO JAMES J. DUNIGAN JR. JOHN M. GALVIN
            REV. TIMOTHY J. QUINN O.F.M. DR. JOSEPH C. SCANIO JOHN F. MAHONEY
            GEORGE J. EVANS DR. JOSEPH P. O'BREIN GERALD A. WHALEN
          </div>
        </div>
      </div>
    )
  }
}
